apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "usecase-backend.fullname" . }}
  labels:
    {{- include "usecase-backend.labels" . | nindent 4 }}
{{- with .Values.ConfigMap }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
