apiVersion: v1
kind: Secret
metadata:
  name: {{ include "usecase-backend.fullname" . }}
  labels:
    {{- include "usecase-backend.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.Secret }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
